# Spring configuration
spring:
  devtools:
    add-properties: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Root@1234}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 60000
      minimum-idle: 5
      maximum-pool-size: 30
      pool-name: blogs-pool
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      timeout: 10000ms
      database: 3
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
      repositories:
        enabled: false
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    mapper:
      accept-case-insensitive-enums: true

# Crypto and JWT configuration
encryption:
  secret:
    password: password
    salt: salt
jwt:
  config:
    secret: VbRSsaYcfTcIdox2DrmJ6nxJCcweiudkn/ik8aXg3g5KtF6U6sKyrvpILdwzMn7ZwxmyOSnK2qatONcQpunYBGSQyvk6xtYVqBy92vs4IWEZhseKRug6C9TftNvmAp0Cs1Jsq0J7yhunN1yPk1IrHk4OJfAU0harnPWDJ/7JtzAuzdNcVYcCfStg7fdtah/5ycQ+OuW1pW6zMKptQC8yPe4hxgQqSQ8D52GVQg==
    ttl: 600000

# CORS configuration
cors:
  max-age: 3600
  allow-credentials: true
  allowed-methods:
  allowed-headers:
  allowed-origins: http://localhost:3000/, http://localhost:4200/
  exposed-headers:

# Open API 3 configuration
springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui
    csrf:
      enabled: true
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
    with-credentials: true

# Logging configuration
logging:
  level:
    root: info
    web: debug
    com.minhlq.blogsservice: error
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 10
  file:
    path: logs
    name: logs/blogs-service.log

# Actuator configuration
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'