# Spring configuration
spring:
  devtools:
    add-properties: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Postgres@123}
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      password: Redis@123
  mvc:
    log-request-details: true
# Crypto and JWT configuration
encryption:
  secret:
    password: password
    salt: salt
jwt:
  config:
    secret: VbRSsaYcfTcIdox2DrmJ6nxJCcweiudkn/ik8aXg3g5KtF6U6sKyrvpILdwzMn7ZwxmyOSnK2qatONcQpunYBGSQyvk6xtYVqBy92vs4IWEZhseKRug6C9TftNvmAp0Cs1Jsq0J7yhunN1yPk1IrHk4OJfAU0harnPWDJ/7JtzAuzdNcVYcCfStg7fdtah/5ycQ+OuW1pW6zMKptQC8yPe4hxgQqSQ8D52GVQg==
    ttl: 600000
# CORS configuration
cors:
  max-age: 3600
  allow-credentials: true
  allowed-methods: GET, POST, PUT, DELETE
  allowed-headers: Authorization, Accept-Language, Content-Type
  allowed-origins: http://localhost:3000/, http://192.168.1.9:3000/
  exposed-headers:
# Open API 3 configuration
springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui
    csrf:
      enabled: true
    display-request-duration: true
    disable-swagger-default-url: true
    use-root-path: true
    with-credentials: true
# Logging configuration
logging:
  level:
    root: info
    com.minhlq.blogs: trace
    web: debug
