# Application configuration
application:
  static-resource-location: /tmp/media/
  static-resource-url: /media/**
# Server configuration
server:
  port: 8080
  forward-headers-strategy: framework
# Spring configuration
spring:
  application:
    name: '@project.name@'
  devtools:
    add-properties: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    mapper:
      accept-case-insensitive-enums: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Postgres@123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 60000
      minimum-idle: 5
      maximum-pool-size: 30
      pool-name: blogs-pool
  jpa:
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        bytecode:
          use_reflection_optimizer: false
  flyway:
    table: schema_history
    validate-migration-naming: true
encryption:
  secret:
    password: password
    salt: salt
jwt:
  config:
    ttl: 3000000
# CORS configuration
cors:
  max-age: 3600
  allow-credentials: true
  allowed-methods: GET, POST, PUT, DELETE
  allowed-headers: Accept, Accept-Language, Authorization, Cache-Control, Content-Type
  allowed-origins: http://localhost:3000
  exposed-headers: Authorization, Set-Cookie
# Actuator configuration
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health", "prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
# Open API 3 configuration
springdoc:
  title: '@project.name@'
  version: '@project.version@'
  description: '@project.description@'
  show-actuator: true
  swagger-ui:
    use-root-path: true
    display-request-duration: true
    with-credentials: true
    groups-order: desc
# Logging configuration
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    root: info
    com.minhlq.blogs: info
