# Spring configuration
spring:
  devtools:
    add-properties: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Postgres@123}
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:Redis@123}
  mvc:
    log-request-details: true
# Crypto and JWT configuration
encryption:
  secret:
    password: ${ENCRYPTION_SECRET_PASSWORD:password}
    salt: ${ENCRYPTION_SECRET_SALT:salt}
jwt:
  config:
    private-key: ${JWT_CONFIG_PRIVATE_KEY:classpath:secure/app.key}
    public-key: ${JWT_CONFIG_PUBLIC_KEY:classpath:secure/app.pub}
    ttl: ${JWT_CONFIG_TTL:300000}
# CORS configuration
cors:
  max-age: ${CORS_MAX_AGE:3600}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET, POST, PUT, DELETE}
  allowed-headers: ${CORS_ALLOWED_HEADERS:Authorization, Accept-Language, Content-Type}
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000/, http://192.168.1.9:3000/}
  exposed-headers: ${CORS_EXPOSED_HEADERS:Authorization, Cookie}
# Open API 3 configuration
springdoc:
  show-actuator: true
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui
    display-request-duration: true
    use-root-path: true
    with-credentials: true
    csrf:
      enabled: true
# Logging configuration
logging:
  level:
    com.minhlq.blogs: trace
    web: debug
