# Application configuration
application:
  title: @project.name@
  version: @project.version@
  description: @project.description@

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /

# Spring configuration
spring:
  profiles:
    active: dev
  application:
    name: blogs_service
