# Spring configuration
spring:
  devtools:
    add-properties: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
encryption:
  secret:
    password: ${ENCRYPTION_SECRET_PASSWORD}
    salt: ${ENCRYPTION_SECRET_SALT}
jwt:
  config:
    private-key: ${JWT_CONFIG_PRIVATE_KEY}
    public-key: ${JWT_CONFIG_PUBLIC_KEY}
    ttl: ${JWT_CONFIG_TTL}
# CORS configuration
cors:
  max-age: ${CORS_MAX_AGE}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS}
  allowed-methods: ${CORS_ALLOWED_METHODS}
  allowed-headers: ${CORS_ALLOWED_HEADERS}
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  exposed-headers: ${CORS_EXPOSED_HEADERS}
# Logging configuration
logging:
  level:
    com.minhlq.blogs: error
