# Spring configuration
spring:
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Postgres@123
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: Redis@123
  mvc:
    log-request-details: true
encryption:
  secret:
    password: password
    salt: salt
jwt:
  config:
    private-key: classpath:secure/app.key
    public-key: classpath:secure/app.pub
    ttl: 3000000
# CORS configuration
cors:
  max-age: 3600
  allow-credentials: true
  allowed-methods: GET, POST, PUT, DELETE
  allowed-headers: Accept, Accept-Language, Authorization, Cache-Control, Content-Type
  allowed-origins: http://localhost:3000/, http://192.168.1.15:3000/
  exposed-headers: Authorization, Set-Cookie
# Open API 3 configuration
springdoc:
  show-actuator: true
  swagger-ui:
    use-root-path: true
    display-request-duration: true
    with-credentials: true
    groups-order: desc
# Logging configuration
logging:
  level:
    web: trace
    com.minhlq.blogs: trace
