# Spring configuration
spring:
  devtools:
    add-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: localhost
      port: 6379
      password:
# Crypto and JWT configuration
encryption:
  secret:
    password:
    salt:
jwt:
  config:
    secret:
    ttl: 600000
# CORS configuration
cors:
  max-age: 3600
  allow-credentials: true
  allowed-methods: GET, POST, PUT, DELETE
  allowed-headers: Authorization, Accept-Language
  allowed-origins: http://localhost:3000/, http://localhost:4200/
  exposed-headers:
# Logging configuration
logging:
  level:
    com.minhlq.blogs: error
