server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: blogs_service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Root@1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      connection-timeout: 30000
      connection-test-query: SELECT 1
      idle-timeout: 30000
      max-lifetime: 60000
      minimum-idle: 5
      maximum-pool-size: 30
      pool-name: blogs-pool
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  redis:
    host: localhost
    port: 6379
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    timeout: 10000ms
    database: 3
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  cache:
    type: redis
  jackson:
    property-naming-strategy: SNAKE_CASE

# JWT config
jwt:
  secret: nRvyYC4soFxBdZ-F-5Nnzz5USXstR1YylsTd-mA0aKtI9HUlriGrtkf-TiuDapkLiUCogO3JOK7kwZisrHp6wA
  session-time: 3600000

# OpenApi config
springdoc:
  version: "@project.version@"
  description: "@project.description@"
  swagger-ui:
    display-request-duration: true
  show-actuator: true

# Logging config
logging:
  pattern:
    console: "%green(%d{${DATETIME_ISO8601}}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
  level:
    com.minhlq.blogsservice: DEBUG
    org.springframework.web: ERROR
    org.hibernate.SQL: INFO
    org.hibernate.type: TRACE

# Actuator config
management:
  server:
    port: 8090
    base-path: /sys
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
