server:
  port: 8080
  servlet:
    context-path: /
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: blogs_service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Root@1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      connection-timeout: 30000
      connection-test-query: SELECT 1
      idle-timeout: 30000
      max-lifetime: 60000
      minimum-idle: 5
      maximum-pool-size: 30
      pool-name: blogs-pool
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  redis:
    host: localhost
    port: 6379
    password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    timeout: 10000ms
    database: 3
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  cache:
    type: redis

# Crypto and Token secrets
crypto:
  secret:
    password: ${CRYPTO_SECRET_PASSWORD:password}
    salt: ${CRYPTO_SECRET_SALT:salt}
jwt:
  config:
    secret: nRvyYC4soFxBdZ-F-5Nnzz5USXstR1YylsTd-mA0aKtI9HUlriGrtkf-TiuDapkLiUCogO3JOK7kwZisrHp6wA
    ttl: 3600000

# CORS Configuration
cors:
  max-age: ${CORS_MAX_AGE:3600}
  allowed-methods: ${CORS_ALLOWED_METHODS:}
  allowed-headers: ${CORS_ALLOWED_HEADERS:}
  exposed-headers: ${CORS_EXPOSED_HEADERS:}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000/, http://localhost:4200/}

# Application configuration
app:
  static-resource-location: /tmp/media/
  static-resource-url: /media/**
  open-weather:
    base-url: https://api.openweathermap.org
    api-key: 878816e6df18cd321379ad9329799e1d

# Open API 3
springdoc:
  name: "@project.name@"
  version: "@project.version@"
  description: "@project.description@"
  swagger-ui:
    display-request-duration: true
  show-actuator: true

# Logging config
logging:
  level:
    com.minhlq.blogsservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.type: TRACE
    # org.apache.http: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:logs}
    name: ${LOGGING_FILE_NAME:logs/application.log}
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 10

# Actuator config
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
