# Spring configuration
spring:
  devtools:
    add-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=blog
    username: postgres
    password: Root@1234
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: localhost
      port: 6379
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
# Crypto and JWT configuration
encryption:
  secret:
    password: password
    salt: salt
jwt:
  config:
    secret: VbRSsaYcfTcIdox2DrmJ6nxJCcweiudkn/ik8aXg3g5KtF6U6sKyrvpILdwzMn7ZwxmyOSnK2qatONcQpunYBGSQyvk6xtYVqBy92vs4IWEZhseKRug6C9TftNvmAp0Cs1Jsq0J7yhunN1yPk1IrHk4OJfAU0harnPWDJ/7JtzAuzdNcVYcCfStg7fdtah/5ycQ+OuW1pW6zMKptQC8yPe4hxgQqSQ8D52GVQg==
    ttl: 600000
# CORS configuration
cors:
  max-age: 3600
  allow-credentials: true
  allowed-methods: GET, POST, PUT, DELETE
  allowed-headers: Authorization, Accept-Language
  allowed-origins: http://localhost:3000/, http://localhost:4200/
  exposed-headers:
# Logging configuration
logging:
  level:
    root: info
    com.minhlq.blogs: error
