# Spring configuration
spring:
  devtools:
    add-properties: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=public}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Root@1234}
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

# Crypto and JWT configuration
encryption:
  secret:
    password: password
    salt: salt
jwt:
  config:
    secret: VbRSsaYcfTcIdox2DrmJ6nxJCcweiudkn/ik8aXg3g5KtF6U6sKyrvpILdwzMn7ZwxmyOSnK2qatONcQpunYBGSQyvk6xtYVqBy92vs4IWEZhseKRug6C9TftNvmAp0Cs1Jsq0J7yhunN1yPk1IrHk4OJfAU0harnPWDJ/7JtzAuzdNcVYcCfStg7fdtah/5ycQ+OuW1pW6zMKptQC8yPe4hxgQqSQ8D52GVQg==
    ttl: 600000

# CORS configuration
cors:
  max-age: 3600
  allow-credentials: true
  allowed-methods:
  allowed-headers:
  allowed-origins: http://localhost:3000/, http://localhost:4200/
  exposed-headers:

# Open API 3 configuration
springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui
    csrf:
      enabled: true
    display-request-duration: true
    disable-swagger-default-url: true
    use-root-path: true
    with-credentials: true

# Logging configuration
logging:
  level:
    root: info
    web: debug
    com.minhlq.blogsservice: trace

# Actuator configuration
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'