apiVersion: v1
kind: Pod
metadata:
  name: Title
  labels:
    app: Title
spec:
  containers:
    - name: Title
      image: adoptopenjdk
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  