scrape_configs:
  - job_name: 'Blogs Services input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'Blogs Services'
