INSERT INTO tags (id, name)
VALUES (1, 'Taunya Hickle'),
       (2, 'Marylynn Kohler'),
       (3, 'Jonas Schmidt'),
       (4, 'Edith Bahringer'),
       (5, 'Maynard Hintz'),
       (6, 'Angella Bernhard'),
       (7, 'Elias Adams'),
       (8, 'Andera Runte'),
       (9, 'Perry Ritchie II'),
       (10, 'Edison Swaniawski'),
       (11, 'Rosana Gutmann'),
       (12, 'Romeo Pouros'),
       (13, 'Francis Stracke'),
       (14, 'Felisa Hudson'),
       (15, 'Regina Veum'),
       (16, 'Nikia Lesch'),
       (17, 'Amina Reinger'),
       (18, 'Jess Koepp IV'),
       (19, 'Piper Prosacco'),
       (20, 'Shirley Kemmer'),
       (21, 'Fae Murphy Jr.'),
       (22, 'Chi Sanford'),
       (23, 'Mckinley Ondricka'),
       (24, 'Ned Wiegand'),
       (25, 'Darius Miller'),
       (26, 'Mignon Ritchie'),
       (27, 'Damian Sauer'),
       (28, 'Mr. Nichole Stokes'),
       (29, 'Dr. Glen Rosenbaum'),
       (30, 'German Jenkins'),
       (31, 'Mr. Beverley Upton'),
       (32, 'Miss Otto Mueller'),
       (33, 'Linn Schneider'),
       (34, 'Edward Kreiger'),
       (35, 'Shanta Bartell'),
       (36, 'Isidro D''Amore'),
       (37, 'Mary Wilderman'),
       (38, 'Mrs. Alfreda Donnelly'),
       (39, 'Narcisa Kerluke'),
       (40, 'Claire Adams'),
       (41, 'Numbers Miller'),
       (42, 'Teena Mante'),
       (43, 'Shalon Streich'),
       (44, 'Perry Treutel'),
       (45, 'Ashly Wiegand'),
       (46, 'Noemi Gorczany'),
       (47, 'Blanca Weimann'),
       (48, 'Brenda Ullrich'),
       (49, 'Jacques Mraz DDS'),
       (50, 'Mr. Pearly Hudson'),
       (51, 'Miss Louis Nitzsche'),
       (52, 'Dr. Geraldo Gerlach'),
       (53, 'Mrs. Almeda Gusikowski'),
       (54, 'Celestine Stroman'),
       (55, 'Doloris Walsh'),
       (56, 'Felice Franecki'),
       (57, 'Patricia Goldner'),
       (58, 'Bennie Hickle'),
       (59, 'Gabriel Upton'),
       (60, 'Kandace Runolfsson'),
       (61, 'Reynaldo Morissette PhD'),
       (62, 'Rickey Anderson III'),
       (63, 'Leeann Boehm'),
       (64, 'Cyrus Ziemann'),
       (65, 'Roger Wilderman'),
       (66, 'Brenna Rosenbaum'),
       (67, 'Mrs. Hiram Rogahn'),
       (68, 'Sang Gulgowski V'),
       (69, 'Rigoberto Sporer'),
       (70, 'Anibal Funk'),
       (71, 'Amanda Welch'),
       (72, 'Travis Gerhold'),
       (73, 'Andrew Wisoky II'),
       (74, 'Lilly Jaskolski'),
       (75, 'Boyce Roberts'),
       (76, 'Kurt Kovacek'),
       (77, 'Mr. Rolf Kulas'),
       (78, 'Seymour Donnelly'),
       (79, 'Grover Walter'),
       (80, 'Denisse Gorczany'),
       (81, 'Parker Denesik I'),
       (82, 'Susanna Douglas PhD'),
       (83, 'Miss Janessa Mayer'),
       (84, 'Whitney Zboncak'),
       (85, 'Lavera Schaefer'),
       (86, 'Juan Pfeffer'),
       (87, 'Ms. Jeanna Boehm'),
       (88, 'Everett Runolfsdottir I'),
       (89, 'Berniece Lind'),
       (90, 'Clyde Ankunding'),
       (91, 'Mrs. Fredric Ruecker'),
       (92, 'Jose Bartell'),
       (93, 'Georgeann Vandervort'),
       (94, 'Eldridge Jaskolski'),
       (95, 'Lester Reichel MD'),
       (96, 'Otelia Heller'),
       (97, 'Gertrudis Kassulke'),
       (98, 'Dorian Abbott'),
       (99, 'Lorina Stroman'),
       (100, 'Carson Kautzer');
